<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../GIPractice.Domain/GIPractice.Domain.csproj" />
    <ProjectReference Include="../GIPractice.Application/GIPractice.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="linq2db" />
    <PackageReference Include="FluentMigrator.Runner" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" />
    <PackageReference Include="FluentMigrator.Runner.MySql" />
    <PackageReference Include="FluentMigrator.Runner.SqlServer" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
</Project>
