<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="linq2db" Version="6.4.0" />
    <PackageVersion Include="FluentMigrator.Runner" Version="8.0.1" />
    <PackageVersion Include="FluentMigrator.Runner.SQLite" Version="8.0.1" />
    <PackageVersion Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
    <PackageVersion Include="FluentMigrator.Runner.MySql" Version="8.0.1" />
    <PackageVersion Include="FluentMigrator.Runner.SqlServer" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="MySqlConnector" Version="2.6.2" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
  </ItemGroup>
</Project>
