// <auto-generated />
using System;
using GIPractice.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIPractice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205191242_SeedOrgansAndOrganAreas")]
    partial class SeedOrgansAndOrganAreas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActiveSubstanceMedicine", b =>
                {
                    b.Property<int>("ActiveSubstancesId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinesId")
                        .HasColumnType("int");

                    b.HasKey("ActiveSubstancesId", "MedicinesId");

                    b.HasIndex("MedicinesId");

                    b.ToTable("ActiveSubstanceMedicine");
                });

            modelBuilder.Entity("BiopsyBottleOrganArea", b =>
                {
                    b.Property<int>("BiopsyBottlesId")
                        .HasColumnType("int");

                    b.Property<int>("OrganAreasId")
                        .HasColumnType("int");

                    b.HasKey("BiopsyBottlesId", "OrganAreasId");

                    b.HasIndex("OrganAreasId");

                    b.ToTable("BiopsyBottleOrganArea");
                });

            modelBuilder.Entity("EndoscopyDiagnosis", b =>
                {
                    b.Property<int>("EndoscopyId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.HasKey("EndoscopyId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("EndoscopyDiagnoses", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.ActiveSubstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActiveSubstances");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Canceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedEndoscopyType")
                        .HasColumnType("int");

                    b.Property<int?>("PreparationProtocolId")
                        .HasColumnType("int");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TookPlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Urgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PreparationProtocolId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.BiopsyBottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndoscopyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndoscopyId");

                    b.HasIndex("PatientId");

                    b.ToTable("BiopsyBottles", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Standard");

                    b.ToTable("Diagnoses", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Specialty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Endoscopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BiopsiesCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EndoscopyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FindingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaidBiopsies")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FindingId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VisitId");

                    b.ToTable("Endoscopies", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Findings", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.InfaiTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("FindingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("FindingId");

                    b.HasIndex("PatientId");

                    b.ToTable("InfaiTests", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LabTypes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PseudoLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles", (string)null);

                    b.HasDiscriminator<string>("MediaType").HasValue("Generic");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Density")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EndoscopyId")
                        .HasColumnType("int");

                    b.Property<int?>("EndoscopyMediaId")
                        .HasColumnType("int");

                    b.Property<int>("FindingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrganAreaId")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndoscopyId");

                    b.HasIndex("EndoscopyMediaId");

                    b.HasIndex("FindingId");

                    b.HasIndex("OrganAreaId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FileId");

                    b.HasIndex("PatientId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Organ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Organs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ESOPHAGUS",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1887),
                            DefaultName = "Esophagus",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1887)
                        },
                        new
                        {
                            Id = 2,
                            Code = "STOMACH",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1890),
                            DefaultName = "Stomach",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1891)
                        },
                        new
                        {
                            Id = 3,
                            Code = "DUODENUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1892),
                            DefaultName = "Duodenum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1892)
                        },
                        new
                        {
                            Id = 4,
                            Code = "JEJUNUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1893),
                            DefaultName = "Jejunum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = 5,
                            Code = "ILEUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1894),
                            DefaultName = "Ileum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1895)
                        },
                        new
                        {
                            Id = 6,
                            Code = "COLON",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1895),
                            DefaultName = "Colon",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1896)
                        },
                        new
                        {
                            Id = 7,
                            Code = "RECTUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1897),
                            DefaultName = "Rectum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1897)
                        },
                        new
                        {
                            Id = 8,
                            Code = "ANUS",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1898),
                            DefaultName = "Anus",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 931, DateTimeKind.Utc).AddTicks(1898)
                        });
                });

            modelBuilder.Entity("GIPractice.Core.Entities.OrganArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrganAreas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ESOPHAGUS_PROX",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5867),
                            DefaultName = "Esophagus proximal third",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5868)
                        },
                        new
                        {
                            Id = 2,
                            Code = "ESOPHAGUS_MID",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5874),
                            DefaultName = "Esophagus middle third",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5874)
                        },
                        new
                        {
                            Id = 3,
                            Code = "ESOPHAGUS_DIST",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5876),
                            DefaultName = "Esophagus distal third",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5876)
                        },
                        new
                        {
                            Id = 4,
                            Code = "GEJ",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5877),
                            DefaultName = "Gastroesophageal junction",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5878)
                        },
                        new
                        {
                            Id = 5,
                            Code = "STOMACH_FUNDUS",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5879),
                            DefaultName = "Stomach fundus",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5879)
                        },
                        new
                        {
                            Id = 6,
                            Code = "STOMACH_BODY",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5880),
                            DefaultName = "Stomach body",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5880)
                        },
                        new
                        {
                            Id = 7,
                            Code = "STOMACH_INCISURA",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5881),
                            DefaultName = "Stomach incisura",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5881)
                        },
                        new
                        {
                            Id = 8,
                            Code = "STOMACH_ANTRUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5882),
                            DefaultName = "Stomach antrum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5882)
                        },
                        new
                        {
                            Id = 9,
                            Code = "PYLORUS",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5883),
                            DefaultName = "Pylorus",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5884)
                        },
                        new
                        {
                            Id = 10,
                            Code = "DUODENUM_BULB",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5885),
                            DefaultName = "Duodenum bulb",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5885)
                        },
                        new
                        {
                            Id = 11,
                            Code = "DUODENUM_SECOND",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5886),
                            DefaultName = "Duodenum second part",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5886)
                        },
                        new
                        {
                            Id = 12,
                            Code = "DUODENUM_THIRD",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5887),
                            DefaultName = "Duodenum third part (horizontal)",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5888)
                        },
                        new
                        {
                            Id = 13,
                            Code = "CECUM",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5889),
                            DefaultName = "Cecum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5889)
                        },
                        new
                        {
                            Id = 14,
                            Code = "ILEOCECAL_VALVE",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5890),
                            DefaultName = "Ileocecal valve",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5890)
                        },
                        new
                        {
                            Id = 15,
                            Code = "COLON_ASC",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5891),
                            DefaultName = "Colon ascending",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5891)
                        },
                        new
                        {
                            Id = 16,
                            Code = "COLON_HEP_FLEX",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5892),
                            DefaultName = "Colon hepatic flexure",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5892)
                        },
                        new
                        {
                            Id = 17,
                            Code = "COLON_TRANS",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5893),
                            DefaultName = "Colon transverse",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5893)
                        },
                        new
                        {
                            Id = 18,
                            Code = "COLON_SPL_FLEX",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5894),
                            DefaultName = "Colon splenic flexure",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5895)
                        },
                        new
                        {
                            Id = 19,
                            Code = "COLON_DESC",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5896),
                            DefaultName = "Colon descending",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5896)
                        },
                        new
                        {
                            Id = 20,
                            Code = "COLON_SIGMOID",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5897),
                            DefaultName = "Colon sigmoid",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5897)
                        },
                        new
                        {
                            Id = 21,
                            Code = "RECTUM_AREA",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5898),
                            DefaultName = "Rectum",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5898)
                        },
                        new
                        {
                            Id = 22,
                            Code = "ANAL_CANAL",
                            CreatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5899),
                            DefaultName = "Anal canal",
                            IsDeleted = false,
                            UpdatedAtUtc = new DateTime(2025, 12, 5, 19, 12, 41, 930, DateTimeKind.Utc).AddTicks(5899)
                        });
                });

            modelBuilder.Entity("GIPractice.Core.Entities.OrganAreaOrgan", b =>
                {
                    b.Property<int>("OrganId")
                        .HasColumnType("int");

                    b.Property<int>("OrganAreaId")
                        .HasColumnType("int");

                    b.HasKey("OrganId", "OrganAreaId");

                    b.HasIndex("OrganAreaId");

                    b.ToTable("OrganAreaOrgans", (string)null);

                    b.HasData(
                        new
                        {
                            OrganId = 1,
                            OrganAreaId = 1
                        },
                        new
                        {
                            OrganId = 1,
                            OrganAreaId = 2
                        },
                        new
                        {
                            OrganId = 1,
                            OrganAreaId = 3
                        },
                        new
                        {
                            OrganId = 1,
                            OrganAreaId = 4
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 4
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 5
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 6
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 7
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 8
                        },
                        new
                        {
                            OrganId = 2,
                            OrganAreaId = 9
                        },
                        new
                        {
                            OrganId = 3,
                            OrganAreaId = 10
                        },
                        new
                        {
                            OrganId = 3,
                            OrganAreaId = 11
                        },
                        new
                        {
                            OrganId = 3,
                            OrganAreaId = 12
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 13
                        },
                        new
                        {
                            OrganId = 5,
                            OrganAreaId = 14
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 14
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 15
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 16
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 17
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 18
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 19
                        },
                        new
                        {
                            OrganId = 6,
                            OrganAreaId = 20
                        },
                        new
                        {
                            OrganId = 7,
                            OrganAreaId = 21
                        },
                        new
                        {
                            OrganId = 8,
                            OrganAreaId = 22
                        });
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patients_PersonalNumber_Format", "[PersonalNumber] IS NOT NULL AND LEN([PersonalNumber]) = 12 AND [PersonalNumber] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("GIPractice.Core.Entities.PreparationProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndoscopyType")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesBowelCleaning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MinimumFastingHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreparationProtocols", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndoscopyId")
                        .HasColumnType("int");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndoscopyId")
                        .IsUnique();

                    b.HasIndex("FileId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualitativeResult")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantitativeResult")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FileId");

                    b.HasIndex("LabId");

                    b.HasIndex("PatientId");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsChronic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Treatments", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.VersionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId", "Version")
                        .IsUnique();

                    b.ToTable("VersionHistory", (string)null);
                });

            modelBuilder.Entity("PatientDiagnosis", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("PatientDiagnoses", (string)null);
                });

            modelBuilder.Entity("TestFinding", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("FindingId")
                        .HasColumnType("int");

                    b.HasKey("TestId", "FindingId");

                    b.HasIndex("FindingId");

                    b.ToTable("TestFindings", (string)null);
                });

            modelBuilder.Entity("TreatmentDiagnosis", b =>
                {
                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.HasKey("TreatmentId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("TreatmentDiagnoses", (string)null);
                });

            modelBuilder.Entity("TreatmentMedicine", b =>
                {
                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.HasKey("TreatmentId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("TreatmentMedicines", (string)null);
                });

            modelBuilder.Entity("Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfVisitUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits", (string)null);
                });

            modelBuilder.Entity("VisitDiagnosis", b =>
                {
                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.HasKey("VisitId", "DiagnosisId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("VisitDiagnoses", (string)null);
                });

            modelBuilder.Entity("GIPractice.Core.Entities.EndoscopyMedia", b =>
                {
                    b.HasBaseType("GIPractice.Core.Entities.MediaFile");

                    b.Property<int>("EndoscopyId")
                        .HasColumnType("int");

                    b.HasIndex("EndoscopyId");

                    b.HasDiscriminator().HasValue("Endoscopy");
                });

            modelBuilder.Entity("ActiveSubstanceMedicine", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.ActiveSubstance", null)
                        .WithMany()
                        .HasForeignKey("ActiveSubstancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiopsyBottleOrganArea", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.BiopsyBottle", null)
                        .WithMany()
                        .HasForeignKey("BiopsyBottlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.OrganArea", null)
                        .WithMany()
                        .HasForeignKey("OrganAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EndoscopyDiagnosis", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Endoscopy", null)
                        .WithMany()
                        .HasForeignKey("EndoscopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Appointment", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.PreparationProtocol", "PreparationProtocol")
                        .WithMany()
                        .HasForeignKey("PreparationProtocolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("PreparationProtocol");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.BiopsyBottle", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Endoscopy", "Endoscopy")
                        .WithMany("BiopsyBottles")
                        .HasForeignKey("EndoscopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("BiopsyBottles")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endoscopy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Doctor", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Lab", "Lab")
                        .WithMany("Doctors")
                        .HasForeignKey("LabId");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Endoscopy", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Finding", null)
                        .WithMany("Endoscopies")
                        .HasForeignKey("FindingId");

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Endoscopies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Visit", "Visit")
                        .WithMany("Endoscopies")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.InfaiTest", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.MediaFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GIPractice.Core.Entities.Finding", null)
                        .WithMany("InfaiTests")
                        .HasForeignKey("FindingId");

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("InfaiTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Observation", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Endoscopy", "Endoscopy")
                        .WithMany("Observations")
                        .HasForeignKey("EndoscopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.EndoscopyMedia", "EndoscopyMedia")
                        .WithMany()
                        .HasForeignKey("EndoscopyMediaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GIPractice.Core.Entities.Finding", "Finding")
                        .WithMany("Observations")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.OrganArea", "OrganArea")
                        .WithMany("Observations")
                        .HasForeignKey("OrganAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endoscopy");

                    b.Navigation("EndoscopyMedia");

                    b.Navigation("Finding");

                    b.Navigation("OrganArea");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Operation", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GIPractice.Core.Entities.MediaFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Operations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("File");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.OrganAreaOrgan", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.OrganArea", "OrganArea")
                        .WithMany("OrganAreaOrgans")
                        .HasForeignKey("OrganAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Organ", "Organ")
                        .WithMany("OrganAreaOrgans")
                        .HasForeignKey("OrganId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organ");

                    b.Navigation("OrganArea");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Report", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Endoscopy", "Endoscopy")
                        .WithOne("Report")
                        .HasForeignKey("GIPractice.Core.Entities.Report", "EndoscopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.MediaFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GIPractice.Core.Entities.Patient", null)
                        .WithMany("BiopsyReports")
                        .HasForeignKey("PatientId");

                    b.Navigation("Endoscopy");

                    b.Navigation("File");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Test", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Doctor", "Doctor")
                        .WithMany("Tests")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GIPractice.Core.Entities.MediaFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GIPractice.Core.Entities.Lab", "Lab")
                        .WithMany("Tests")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Tests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("File");

                    b.Navigation("Lab");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Treatment", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Doctor", "Doctor")
                        .WithMany("Treatments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientDiagnosis", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestFinding", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreatmentDiagnosis", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreatmentMedicine", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GIPractice.Core.Entities.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Visit", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Appointment", "Appointment")
                        .WithOne("Visit")
                        .HasForeignKey("Visit", "AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GIPractice.Core.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VisitDiagnosis", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GIPractice.Core.Entities.EndoscopyMedia", b =>
                {
                    b.HasOne("GIPractice.Core.Entities.Endoscopy", "Endoscopy")
                        .WithMany("MediaFiles")
                        .HasForeignKey("EndoscopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endoscopy");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Appointment", b =>
                {
                    b.Navigation("Visit");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Tests");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Endoscopy", b =>
                {
                    b.Navigation("BiopsyBottles");

                    b.Navigation("MediaFiles");

                    b.Navigation("Observations");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Finding", b =>
                {
                    b.Navigation("Endoscopies");

                    b.Navigation("InfaiTests");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Lab", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Organ", b =>
                {
                    b.Navigation("OrganAreaOrgans");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.OrganArea", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("OrganAreaOrgans");
                });

            modelBuilder.Entity("GIPractice.Core.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BiopsyBottles");

                    b.Navigation("BiopsyReports");

                    b.Navigation("Endoscopies");

                    b.Navigation("InfaiTests");

                    b.Navigation("Operations");

                    b.Navigation("Tests");

                    b.Navigation("Treatments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Visit", b =>
                {
                    b.Navigation("Endoscopies");
                });
#pragma warning restore 612, 618
        }
    }
}
