@GIPractice.Api_HostAddress = https://localhost:7028

GET {{GIPractice.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{GIPractice.Api_HostAddress}}/health/ready
Accept: application/json

###
